Repository Record-Timeline/Front, pull requests merged in 2024-06, with the labels that each got.

#15 Rtl 93 [FE] 검색 페이지 연동
  src/components/common/NavigationBar.jsx
  src/components/main/RecoderRecommendation.jsx
  src/components/main/SearchPostBox.jsx
  src/components/main/SearchRecoderBox.jsx
  src/pages/MainTimeline.jsx
  src/pages/Search.jsx
  src/pages/SearchResult.jsx
Labels: Feature, 김소희

#16 Rtl 90 fe 메인 타임라인 연동
  .idea/inspectionProfiles/Project_Default.xml
  .idea/workspace.xml
  src/components/common/AlertDialog.jsx
  src/components/common/DatePickerValue.jsx
  src/components/common/MyProfile.jsx
  src/components/timeline/MainTimelineInput.jsx
  src/components/timeline/MainTimelineItem.jsx
  src/pages/MainTimeline.jsx
  src/pages/SubTimeline.jsx
Labels: Feature, 김사라

#18 Rtl 92 fe 서브 타임라인 연동
  package-lock.json
  package.json
  src/components/post/PostEditor.jsx
  src/components/subTimeline/CreateSubTimelinePost.jsx
  src/components/subTimeline/ReadSubTimelinePost.jsx
  src/components/subTimeline/SubTimelineInput.jsx
  src/components/subTimeline/SubTimelineItem.jsx
  src/components/timeline/MainTimelineItem.jsx
  src/pages/MainTimeline.jsx
  src/pages/SubTimeline.jsx
Labels: 김사라
