Repository Record-Timeline/Front, pull requests merged in 2024-08, with the labels that each got.

#28 Rtl 100 [FE] 회원정보 수정 및 자잘한 수정사항
  src/assets/images/logo.png
  src/assets/images/recodeTimelineLogo.svg
  src/components/common/NavigationBar.jsx
  src/components/profile/PasswordChangeModal.jsx
  src/pages/Main.jsx
  src/pages/ModifyProfile.jsx
  src/pages/Search.jsx
Labels: Feature, Refactor, 김소희

#29 Rtl 110 [FE] 팔로잉 목록 페이지
  src/App.js
  src/components/common/NavigationBar.jsx
  src/components/follow/FollowerUser.jsx
  src/pages/Follow.jsx
Labels: Feature

#30 Rtl 111 [FE] 비밀번호 찾기 페이지
  src/App.js
  src/actions/actions.js
  src/components/common/Header.jsx
  src/components/common/NavigationBar.jsx
  src/components/main/PostBox.jsx
  src/components/main/PostRecommendation.jsx
  src/components/signUp/FieldStep.jsx
  src/pages/FindPassword.jsx
  src/pages/FindPasswordCertification.jsx
  src/pages/FindPasswordChange.jsx
  src/pages/Main.jsx
  src/pages/PasswordChangeComplete.jsx
  src/pages/SearchResult.jsx
  src/pages/SignUp.jsx
  src/reducers/reducers.js
Labels: Feature, Refactor, 김소희

#32 Rtl 112 fe 팔로우 팔로잉 연동
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/components/common/AlertDialog.jsx
  src/components/common/MyProfile.jsx
  src/components/common/OthersProfile.jsx
  src/components/othersTimeline/OthersSubTimelinePost.jsx
  src/components/othersTimeline/OthersTimelineItem.jsx
  src/components/subTimeline/ReadSubTimelinePost.jsx
  src/components/timeline/CareerModal.jsx
  src/components/timeline/MainTimelineInput.jsx
  src/components/timeline/MainTimelineItem.jsx
  src/pages/Bookmark.jsx
  src/pages/OthersSubTimeline.jsx
  src/pages/SubTimeline.jsx
Labels: Feature, 김사라

#33 Rtl 113 fe 북마크 좋아요 연동
  src/App.js
  src/components/common/Header.jsx
  src/components/common/MyProfile.jsx
  src/components/common/OthersProfile.jsx
  src/components/common/PostBox.jsx
  src/components/othersTimeline/OthersSubTimelineItem.jsx
  src/components/othersTimeline/OthersSubTimelinePost.jsx
  src/components/othersTimeline/OthersTimelineItem.jsx
  src/components/subTimeline/CreateSubTimelinePost.jsx
  src/components/subTimeline/ReadSubTimelinePost.jsx
  src/components/subTimeline/SubTimelineItem.jsx
  src/components/timeline/MainTimelineInput.jsx
  src/components/timeline/MainTimelineItem.jsx
  src/pages/Bookmark.jsx
  src/pages/MainTimeline.jsx
  src/pages/OthersMainTimeline.jsx
  src/pages/OthersSubTimeline.jsx
  src/pages/SearchResult.jsx
  src/pages/SubTimeline.jsx
Labels: Feature, 김사라

#34 Rtl 33 fe 북마크한 서브타임 게시글 목록 ui
  src/pages/SubTimeline.jsx
Labels: Feature, BugFix, Refactor, 김사라

#35 Rtl 114 fe 경력사항 UI 및 연동
  package-lock.json
  package.json
  src/App.js
  src/components/career/Career.jsx
  src/components/career/CareerInput.jsx
  src/components/career/Certificate.jsx
  src/components/career/CertificateInput.jsx
  src/components/career/Education.jsx
  src/components/career/EducationInput.jsx
  src/components/career/Language.jsx
  src/components/career/LanguageInput.jsx
  src/components/career/NoneData.jsx
  src/components/common/DatePickerValue.jsx
  src/components/common/MyProfile.jsx
  src/components/common/OthersProfile.jsx
  src/components/timeline/CareerModal.jsx
  src/pages/Bookmark.jsx
  src/pages/MainTimeline.jsx
Labels: Feature, 김사라

#36 Rtl 120 fe 진행중 체크 연동
  src/components/othersTimeline/OthersSubTimelineItem.jsx
  src/components/othersTimeline/OthersSubTimelinePost.jsx
  src/components/othersTimeline/OthersTimelineItem.jsx
  src/components/subTimeline/ReadSubTimelinePost.jsx
  src/components/subTimeline/SubTimelineItem.jsx
  src/components/timeline/MainTimelineItem.jsx
  src/pages/MainTimeline.jsx
  src/pages/OthersMainTimeline.jsx
  src/pages/OthersSubTimeline.jsx
  src/pages/SubTimeline.jsx
Labels: Feature, BugFix, Refactor, 김사라
